base_model: meta-llama/Llama-2-7b-chat-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: true
load_in_4bit: false

datasets:
  - path: OpenMed/Medical-Reasoning-SFT-Trinity-Mini
    split: train
    type: chat_template
dataset_prepared_path: /workspace/axolotl-datasets/Llama-2-7b-chat/Medical-Reasoning-SFT-Trinity-Mini
val_set_size: 0.05
output_dir: /workspace/axolotl-outputs/Llama-2-7b-chat-Medical-Reasoning-SFT-Trinity-Mini_bs8_2e-4

sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 64
lora_dropout: 0.00
lora_target_linear: true
lora_modules_to_save:
  - embed_tokens
  - lm_head
merge_lora: true

wandb_project: Medical-Reasoning-SFT-Trinity-Mini
wandb_entity: wtkuan
wandb_watch: all
wandb_name: Llama-2-7b-chat-Medical-Reasoning-SFT-Trinity-Mini_bs8_2e-4
wandb_log_model: "false"

gradient_accumulation_steps: 1
micro_batch_size: 8
steps: 1000
early_stopping_patience: 2
optimizer: adamw_8bit
lr_scheduler: linear
learning_rate: 2e-4
weight_decay: 0.01
warmup_steps: 5

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

eval_steps: 60 
save_steps: 60
save_total_limit: 1
load_best_model_at_end: true
special_tokens: